# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class tela_usuario(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(680, 469)
        Dialog.setStyleSheet("background-color: cyan")
        self.Mensagem_user = QtWidgets.QLabel(Dialog)
        self.Mensagem_user.setGeometry(QtCore.QRect(20, 20, 611, 31))
        self.Mensagem_user.setStyleSheet("")
        self.Mensagem_user.setObjectName("Mensagem_user")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 130, 301, 41))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(220, 170, 231, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(210, 200, 101, 31))
        self.pushButton.setStyleSheet("QPushButton {background-color: #A3C1DA; color: blue;}\n"
"QPushButton:hover:!pressed {border: 3px solid green;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 200, 101, 31))
        self.pushButton_2.setStyleSheet("QPushButton {background-color: #A3C1DA; color: blue;}\n"
"QPushButton:hover:!pressed {border: 3px solid green;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 260, 101, 31))
        self.pushButton_3.setStyleSheet("QPushButton {background-color: #A3C1DA; color: blue;}\n"
"QPushButton:hover:!pressed {border: 3px solid green;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 260, 101, 31))
        self.pushButton_4.setStyleSheet("QPushButton {background-color: #A3C1DA; color: blue;}\n"
"QPushButton:hover:!pressed {border: 3px solid green;}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(330, 190, 20, 101))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 320, 75, 23))
        self.pushButton_5.setStyleSheet("QPushButton {background-color: #A3C1DA; color: blue;}\n"
"QPushButton:hover:!pressed {border: 3px solid yellow;}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(500, 140, 111, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("POO2_TELA_BANCO/usuario1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(310, 380, 75, 23))
        self.pushButton_6.setStyleSheet("QPushButton {background-color: #A3C1DA; color: red;}\n"
"QPushButton:hover:!pressed {border: 2px solid red;}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(290, 360, 118, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Ocultar_button = QtWidgets.QPushButton(Dialog)
        self.Ocultar_button.setGeometry(QtCore.QRect(200, 60, 31, 23))
        self.Ocultar_button.setStyleSheet("background-repeat: no-repeat;border-radius: 7px; border-style:solid;border-width:1px;border-color:blue;")
        self.Ocultar_button.setText("")
        self.Ocultar_button.setObjectName("Ocultar_button")
        self.Saldo_label = QtWidgets.QLabel(Dialog)
        self.Saldo_label.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.Saldo_label.setObjectName("Saldo_label")
        self.Saldo_set = QtWidgets.QLabel(Dialog)
        self.Saldo_set.setGeometry(QtCore.QRect(100, 60, 91, 21))
        self.Saldo_set.setObjectName("Saldo_set")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Mensagem_user.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#0000ff;\"/></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#0000ff;\">O QUE DESEJA FAZER?</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "DEPÓSITO"))
        self.pushButton_2.setText(_translate("Dialog", "TRANSFERÊNCIA"))
        self.pushButton_3.setText(_translate("Dialog", "SAQUE"))
        self.pushButton_4.setText(_translate("Dialog", "PEDIR EXTRATO"))
        self.pushButton_5.setText(_translate("Dialog", "LogOut"))
        self.pushButton_6.setText(_translate("Dialog", "SAIR"))
        self.Saldo_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#0000ff;\">SALDO:</span></p></body></html>"))
        self.Saldo_set.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#0000ff;\">123456789.9</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = tela_usuario()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
